USE QuanLyThuVien;
GO

IF OBJECT_ID('dbo.SACHYEUTHICH', 'U') IS NULL
BEGIN
    CREATE TABLE SACHYEUTHICH (
        MaYeuThich VARCHAR(30) PRIMARY KEY,
        MaDocGia VARCHAR(30) NOT NULL,
        MaDauSach VARCHAR(30) NOT NULL,
        NgayThem DATETIME2 NOT NULL DEFAULT SYSDATETIME(),

        CONSTRAINT FK_SYT_DOCGIA
            FOREIGN KEY (MaDocGia) REFERENCES DOCGIA(MaDocGia),

        CONSTRAINT FK_SYT_DAUSACH
            FOREIGN KEY (MaDauSach) REFERENCES DAUSACH(MaDauSach),

        CONSTRAINT UQ_SYT_DOCGIA_DAUSACH
            UNIQUE (MaDocGia, MaDauSach)
    );
END
GO

IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IX_SACHYEUTHICH_DOCGIA_NGAYTHEM'
      AND object_id = OBJECT_ID('dbo.SACHYEUTHICH')
)
BEGIN
    CREATE INDEX IX_SACHYEUTHICH_DOCGIA_NGAYTHEM
    ON SACHYEUTHICH(MaDocGia, NgayThem DESC);
END
GO
