USE QuanLyThuVien;
GO

IF OBJECT_ID('dbo.SACHYEUTHICH', 'U') IS NULL
BEGIN
    CREATE TABLE SACHYEUTHICH (
        MaYeuThich VARCHAR(30) PRIMARY KEY,
        MaDocGia VARCHAR(30) NOT NULL,
        MaDauSach VARCHAR(30) NOT NULL,
        NgayThem DATETIME2 NOT NULL DEFAULT SYSDATETIME(),

        CONSTRAINT FK_SYT_DOCGIA
            FOREIGN KEY (MaDocGia) REFERENCES DOCGIA(MaDocGia),

        CONSTRAINT FK_SYT_DAUSACH
            FOREIGN KEY (MaDauSach) REFERENCES DAUSACH(MaDauSach),

        CONSTRAINT UQ_SYT_DOCGIA_DAUSACH
            UNIQUE (MaDocGia, MaDauSach)
    );
END
GO

IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IX_SACHYEUTHICH_DOCGIA_NGAYTHEM'
      AND object_id = OBJECT_ID('dbo.SACHYEUTHICH')
)
BEGIN
    CREATE INDEX IX_SACHYEUTHICH_DOCGIA_NGAYTHEM
    ON SACHYEUTHICH(MaDocGia, NgayThem DESC);
END
GO

IF OBJECT_ID('dbo.SACHYEUTHICH', 'U') IS NOT NULL
AND NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IX_SACHYEUTHICH_DAUSACH'
      AND object_id = OBJECT_ID('dbo.SACHYEUTHICH')
)
BEGIN
    CREATE INDEX IX_SACHYEUTHICH_DAUSACH
    ON SACHYEUTHICH(MaDauSach);
END
GO

IF OBJECT_ID('dbo.CUONSACH', 'U') IS NOT NULL
AND NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IX_CUONSACH_DAUSACH_TRANGTHAI_NGAYNHAP'
      AND object_id = OBJECT_ID('dbo.CUONSACH')
)
BEGIN
    CREATE INDEX IX_CUONSACH_DAUSACH_TRANGTHAI_NGAYNHAP
    ON CUONSACH(MaDauSach, MaTrangThai, NgayNhapSach DESC);
END
GO

IF OBJECT_ID('dbo.CHITIETPHIEUMUON', 'U') IS NOT NULL
AND NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IX_CTPM_CUONSACH_NGAYMUON'
      AND object_id = OBJECT_ID('dbo.CHITIETPHIEUMUON')
)
BEGIN
    CREATE INDEX IX_CTPM_CUONSACH_NGAYMUON
    ON CHITIETPHIEUMUON(MaCuonSach, NgayMuon DESC);
END
GO

IF OBJECT_ID('dbo.DANHGIA', 'U') IS NOT NULL
AND NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IX_DANHGIA_DAUSACH_TRANGTHAI_SOSAO'
      AND object_id = OBJECT_ID('dbo.DANHGIA')
)
BEGIN
    CREATE INDEX IX_DANHGIA_DAUSACH_TRANGTHAI_SOSAO
    ON DANHGIA(MaDauSach, TrangThai, SoSao);
END
GO
