USE QuanLyThuVien;

SET XACT_ABORT ON;

BEGIN TRY
    BEGIN TRANSACTION;

    IF OBJECT_ID(N'dbo.CUONSACH_TRANGTHAI_EVENT', N'U') IS NULL
    BEGIN
        CREATE TABLE dbo.CUONSACH_TRANGTHAI_EVENT (
            MaSuKien BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
            MaCuonSach VARCHAR(40) NOT NULL,
            HanhDong VARCHAR(40) NOT NULL,
            TrangThaiTruoc VARCHAR(30) NOT NULL,
            TrangThaiSau VARCHAR(30) NOT NULL,
            MucDo VARCHAR(20) NULL,
            LoaiHong NVARCHAR(600) NULL,
            MoTa NVARCHAR(1000) NULL,
            LyDo NVARCHAR(500) NOT NULL,
            MaTaiKhoan VARCHAR(30) NOT NULL,
            ThoiGian DATETIME2 NOT NULL CONSTRAINT DF_CUONSACH_TT_EVENT_THOIGIAN DEFAULT SYSDATETIME(),
            CONSTRAINT FK_CUONSACH_TT_EVENT_CUONSACH FOREIGN KEY (MaCuonSach) REFERENCES dbo.CUONSACH(MaCuonSach),
            CONSTRAINT FK_CUONSACH_TT_EVENT_TRUOC FOREIGN KEY (TrangThaiTruoc) REFERENCES dbo.TRANGTHAICUONSACH(MaTrangThai),
            CONSTRAINT FK_CUONSACH_TT_EVENT_SAU FOREIGN KEY (TrangThaiSau) REFERENCES dbo.TRANGTHAICUONSACH(MaTrangThai),
            CONSTRAINT FK_CUONSACH_TT_EVENT_TAIKHOAN FOREIGN KEY (MaTaiKhoan) REFERENCES dbo.TAIKHOAN(MaTaiKhoan)
        );
    END;

    IF OBJECT_ID(N'dbo.CUONSACH_VITRI_EVENT', N'U') IS NULL
    BEGIN
        CREATE TABLE dbo.CUONSACH_VITRI_EVENT (
            MaSuKien BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
            MaCuonSach VARCHAR(40) NOT NULL,
            MaViTriTruoc VARCHAR(30) NOT NULL,
            MaViTriSau VARCHAR(30) NOT NULL,
            LyDo NVARCHAR(500) NOT NULL,
            MaTaiKhoan VARCHAR(30) NOT NULL,
            ThoiGian DATETIME2 NOT NULL CONSTRAINT DF_CUONSACH_VT_EVENT_THOIGIAN DEFAULT SYSDATETIME(),
            CONSTRAINT FK_CUONSACH_VT_EVENT_CUONSACH FOREIGN KEY (MaCuonSach) REFERENCES dbo.CUONSACH(MaCuonSach),
            CONSTRAINT FK_CUONSACH_VT_EVENT_TRUOC FOREIGN KEY (MaViTriTruoc) REFERENCES dbo.VITRISACH(MaViTri),
            CONSTRAINT FK_CUONSACH_VT_EVENT_SAU FOREIGN KEY (MaViTriSau) REFERENCES dbo.VITRISACH(MaViTri),
            CONSTRAINT FK_CUONSACH_VT_EVENT_TAIKHOAN FOREIGN KEY (MaTaiKhoan) REFERENCES dbo.TAIKHOAN(MaTaiKhoan)
        );
    END;

    IF NOT EXISTS (
        SELECT 1 FROM sys.indexes
        WHERE name = N'IX_CUONSACH_TT_EVENT_COPY_TIME'
          AND object_id = OBJECT_ID(N'dbo.CUONSACH_TRANGTHAI_EVENT')
    )
        CREATE INDEX IX_CUONSACH_TT_EVENT_COPY_TIME
            ON dbo.CUONSACH_TRANGTHAI_EVENT(MaCuonSach, ThoiGian DESC, MaSuKien DESC);

    IF NOT EXISTS (
        SELECT 1 FROM sys.indexes
        WHERE name = N'IX_CUONSACH_VT_EVENT_COPY_TIME'
          AND object_id = OBJECT_ID(N'dbo.CUONSACH_VITRI_EVENT')
    )
        CREATE INDEX IX_CUONSACH_VT_EVENT_COPY_TIME
            ON dbo.CUONSACH_VITRI_EVENT(MaCuonSach, ThoiGian DESC, MaSuKien DESC);

    COMMIT TRANSACTION;
END TRY
BEGIN CATCH
    IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION;
    THROW;
END CATCH;
