USE QuanLyThuVien;

SET XACT_ABORT ON;

BEGIN TRY
    BEGIN TRANSACTION;

    IF COL_LENGTH('dbo.TAIKHOAN', 'MustChangePassword') IS NULL
        ALTER TABLE dbo.TAIKHOAN ADD MustChangePassword BIT NOT NULL
            CONSTRAINT DF_TAIKHOAN_MUST_CHANGE_PASSWORD DEFAULT 0 WITH VALUES;

    IF COL_LENGTH('dbo.TAIKHOAN', 'PasswordChangedAt') IS NULL
        ALTER TABLE dbo.TAIKHOAN ADD PasswordChangedAt DATETIME2 NULL;

    IF COL_LENGTH('dbo.TAIKHOAN', 'TokenVersion') IS NULL
        ALTER TABLE dbo.TAIKHOAN ADD TokenVersion BIGINT NOT NULL
            CONSTRAINT DF_TAIKHOAN_TOKEN_VERSION DEFAULT 0 WITH VALUES;

    EXEC(N'UPDATE dbo.TAIKHOAN
        SET PasswordChangedAt = COALESCE(PasswordChangedAt, NgayTao)
        WHERE PasswordChangedAt IS NULL');

    IF OBJECT_ID(N'dbo.DOCGIA_PASSWORD_RESET_EVENT', N'U') IS NULL
    BEGIN
        CREATE TABLE dbo.DOCGIA_PASSWORD_RESET_EVENT (
            MaSuKien BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
            MaDocGia VARCHAR(30) NOT NULL,
            MaTaiKhoan VARCHAR(30) NOT NULL,
            MaTaiKhoanThucHien VARCHAR(30) NOT NULL,
            PhuongThucXacMinh VARCHAR(40) NOT NULL,
            LyDo NVARCHAR(500) NOT NULL,
            KetQua VARCHAR(20) NOT NULL,
            ThoiGian DATETIME2 NOT NULL CONSTRAINT DF_DOCGIA_PASSWORD_RESET_TIME DEFAULT SYSDATETIME(),
            CONSTRAINT CK_DOCGIA_PASSWORD_RESET_RESULT CHECK (KetQua IN ('DENIED', 'SUCCESS')),
            CONSTRAINT FK_DOCGIA_PASSWORD_RESET_READER FOREIGN KEY (MaDocGia) REFERENCES dbo.DOCGIA(MaDocGia),
            CONSTRAINT FK_DOCGIA_PASSWORD_RESET_ACCOUNT FOREIGN KEY (MaTaiKhoan) REFERENCES dbo.TAIKHOAN(MaTaiKhoan),
            CONSTRAINT FK_DOCGIA_PASSWORD_RESET_ACTOR FOREIGN KEY (MaTaiKhoanThucHien) REFERENCES dbo.TAIKHOAN(MaTaiKhoan)
        );
    END;

    IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_READER_PASSWORD_RESET_READER_TIME'
                   AND object_id = OBJECT_ID(N'dbo.DOCGIA_PASSWORD_RESET_EVENT'))
        CREATE INDEX IX_READER_PASSWORD_RESET_READER_TIME
            ON dbo.DOCGIA_PASSWORD_RESET_EVENT(MaDocGia, ThoiGian DESC);

    IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_READER_PASSWORD_RESET_ACTOR_TIME'
                   AND object_id = OBJECT_ID(N'dbo.DOCGIA_PASSWORD_RESET_EVENT'))
        CREATE INDEX IX_READER_PASSWORD_RESET_ACTOR_TIME
            ON dbo.DOCGIA_PASSWORD_RESET_EVENT(MaTaiKhoanThucHien, ThoiGian DESC);

    COMMIT TRANSACTION;
END TRY
BEGIN CATCH
    IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION;
    THROW;
END CATCH;
